services:
  - type: web
    name: profile-enhancer
    env: python
    buildCommand: pip install -r profile_enhancer/requirements.txt
    startCommand: uvicorn score:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000