services:
  - type: web
    name: profile-enhancer
    env: python
    # This buildCommand now assumes the "Root Directory" is set to 'profile_enhancer'
    buildCommand: pip install -r requirements.txt
    # This startCommand now correctly references score.py within the 'profile_enhancer' root
    startCommand: uvicorn score:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000